ALTER TABLE approvals ADD COLUMN resource_type VARCHAR(32) DEFAULT 'lead' NOT NULL;
ALTER TABLE approvals ADD COLUMN resource_id VARCHAR(40) DEFAULT '' NOT NULL;
ALTER TABLE approvals ADD COLUMN expires_at VARCHAR(40) DEFAULT '' NOT NULL;
