ALTER TABLE owner_tasks ADD COLUMN due_ready BOOLEAN DEFAULT 0 NOT NULL;
ALTER TABLE owner_tasks ADD COLUMN block_reason VARCHAR(32) DEFAULT '' NOT NULL;
ALTER TABLE webhook_events ADD COLUMN claimed_at VARCHAR(64) DEFAULT '' NOT NULL;
ALTER TABLE lead_follow_ups ADD COLUMN send_ready BOOLEAN DEFAULT 0 NOT NULL;
ALTER TABLE lead_follow_ups ADD COLUMN block_reason VARCHAR(32) DEFAULT '' NOT NULL;
