"""Historical owner task identifiers retained for persisted records and typed handlers."""

from enum import StrEnum


class OwnerTaskType(StrEnum):
    NOTE = "note"
    PREFERENCE = "preference"
    APPROVAL = "approval"
    SALES = "sales"
    ANALYTICS = "analytics"
    RESEARCH = "research"
    LINKEDIN = "linkedin"
    SUPPORT = "support"
    MEETING_DEBRIEF = "meeting_debrief"
    DAILY_BRIEF = "daily_brief"
    WEEKLY_BRIEF = "weekly_brief"
    LEAD_REVIEW = "lead_review"
    CONTENT_IDEA = "content_idea"
    GMAIL_SUMMARY = "gmail_summary"
    GMAIL_DRAFT = "gmail_draft"
    SEO = "seo"
    CALENDAR = "calendar"
    CALENDAR_WRITE = "calendar_write"
    OWNER_NOTIFY = "owner_notify"
    MEETING_BRIEF = "meeting_brief"
    HUMAN_TAKEOVER = "human_takeover"
    HUMAN_TAKEOVER_RESUME = "human_takeover_resume"
    CONVERSATION_SCOPE = "conversation_scope"
    HOT_LEADS = "hot_leads"
    PENDING_APPROVALS = "pending_approvals"
    WEBSITE_CONVERSATIONS = "website_conversations"
    LEAD_OUTREACH = "lead_outreach"
    OWNER_STATUS = "owner_status"
    OPERATOR_SNAPSHOT = "operator_snapshot"
